language: python

python:
  - "2.7"

install:
  - cd xls2xml && pip install -r requirements.txt && cd ..

script:
  - cd xls2xml && pylint --errors-only ./xls2xml/ && cd ..
  - cd xls2xml && pylint --errors-only ./tests/ && cd ..
  - cd xls2xml/tests && pytest && cd ../..
